### ISSUE TITLE
Component doesn't render on SSG

### ISSUE THREAD

**Issue by sohail-ansari02** [omnedia/ngx-starry-sky#1]
I created an hero section and it should be prerender for SEO. 
I can't add condition to hero section to render it on client side. 

Getting of window is not defined from `init` method. 

I think this issue is in all other components as well.

**Comment by xSentry** [comment]
Fixed here [Commit](https://github.com/omnedia/ngx-starry-sky/commit/d69a6c3103f44651ad98249b15f52995388440a6)
